version: '3.7'

services:

  tdd-service:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - .:/usr/src/service-tdd
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@tdd-service-db:5432/users_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@tdd-service-db:5432/users_test
    depends_on:
      - tdd-service-db

  tdd-service-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres